### ISSUE TITLE
[Question] Cant load other soundfont in iOS

### ISSUE THREAD

**Issue by tnvinh2711** [melihhakanpektas/flutter_midi_pro#16]
Hello, currently I'm testing examples on iOS with some different soundfonts. However, all soundfonts produce the same output. Do you think I did something wrong?

https://github.com/melihhakanpektas/flutter_midi_pro/assets/34644363/7c7590bf-81f1-4bad-b851-81bd36fc40f2

A sample sound font in my demo:
[Flute.sf2.zip](https://github.com/melihhakanpektas/flutter_midi_pro/files/15014486/Flute.sf2.zip)

**Comment by melihhakanpektas** [comment]
You can check the new version of the flutter_midi_pro plugin. Nearly everything changed in this package but you can manage everything of the soundfont and midi channels 🚀

**Comment by tnvinh2711** [comment]
Great work!! Thank you very much!!

**Comment by B18DCCN347** [comment]
Sorry, but has this error of loading many soundfonts been fixed on iOS?
