### ISSUE TITLE
FAILURE: Build failed with an exception - Don´t run

### ISSUE THREAD

**Issue by marcosarantesj** [melihhakanpektas/flutter_midi_pro#19]
[CXX1300] CMake '3.22.1' was not found in SDK, PATH, or by cmake.dir property.
[CXX1416] Could not find Ninja on PATH or in SDK CMake bin folders.
[CXX1300] CMake '3.22.1' was not found in SDK, PATH, or by cmake.dir property.
[CXX1416] Could not find Ninja on PATH or in SDK CMake bin folders.
[CXX1300] CMake '3.22.1' was not found in SDK, PATH, or by cmake.dir property.
[CXX1416] Could not find Ninja on PATH or in SDK CMake bin folders.

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 3s
Error: Gradle task assembleDebug failed with exit code 1

**Comment by melihhakanpektas** [comment]
I forgot to add this to the readme. The Fluidsynth library used in Android needs to be built with CMake. Especially for `flutter_midi_pro`, CMake version 3.22.1 must be installed. To install CMake:

### 1. Open Android Studio.


### 2. Go to **Tools** -> **SDK Manager**.

![Screenshot 2024-04-28 021839](https://github.com/melihhakanpektas/flutter_midi_pro/assets/108405689/60a36384-98e7-4576-b0e4-b805231b7554)

### 3. Open the **SDK Tools** tab and click on the **Show Package Details** checkbox.
![Screenshot 2024-04-28 022433](https://github.com/melihhakanpektas/flutter_midi_pro/assets/108405689/658bc387-d7b9-4737-9a56-b26da9806218)
### 4. From the list, select the CMake version 3.22.1 under the CMake section and click the **Apply** button.
![Screenshot 2024-04-28 022521](https://github.com/melihhakanpektas/flutter_midi_pro/assets/108405689/35f6a6b7-6cc7-4cfc-bd09-735a82993746)

### 5. Confirm the installation. Once the installation is complete, the build should succeed.
