### ISSUE TITLE
[Question] Cant load other soundfont in iOS

### ISSUE THREAD

**Issue by B18DCCN347** [melihhakanpektas/flutter_midi_pro#23]
Similar to #16, after upgrading to 3.0.1 I still have the problem of not being able to download many soundfonts on iOS devices. Is there any way to fix this problem?

**Comment by melihhakanpektas** [comment]
When and how are you experiencing the problem? If you explain with more details, I can assist you better. Especially, list the steps you have taken, and if possible, send a code example.
