### ISSUE TITLE
Sound is too low 

### ISSUE THREAD

**Issue by sohamprodt** [melihhakanpektas/flutter_midi_pro#26]
Hi @melihhakanpektas  its seems that even after full volume the sound generated is too low. I am passing velocity at full level i.e 127. Can you help me out of this?

**Comment by sohamprodt** [comment]
Hi @melihhakanpektas  I have solution to it..for now I have forked and made changes in native-lib.cpp file by adding     `fluid_settings_setnum(settings,` "synth.gain", volume);`

**Comment by melihhakanpektas** [comment]
Hello, the level of gain is 0.6 default. I set this level to 1.0 before using the setting object. I added your code in version 3.1.1. Thank you for your contributions.
