### ISSUE TITLE
The example doesn't play any sound on Android on macOS

### ISSUE THREAD

**Issue by aalex** [melihhakanpektas/flutter_midi_pro#5]
The example doesn't play any sound on Android on macOS

## To reproduce
- Build the example for iOS. It plays sounds as expected.
- Build the example for Android on an M1 macOS.
- We would expect it to play some sounds,
- but it doesn't.

## Screenshot
<img width="353" alt="image" src="https://github.com/MelihHakanPektas/flutter_midi_pro/assets/293677/89031e7a-9cae-4542-acb5-05ee33dd851a">

**Comment by melihhakanpektas** [comment]
This package more stable now.
