### ISSUE TITLE
Handle multiple instruments in font file

### ISSUE THREAD

**Issue by KapitanPL** [melihhakanpektas/flutter_midi_pro#6]
Hi @melihhakanpektas , 

I am new generating sound. But I found that most sf2 files contains multiple instruments. 
However this lib does not seem to care.

Is there any support for that? Or could you give me a hint how to work with that? (If successfull I would be more then willing to create a pull request.)

**Comment by melihhakanpektas** [comment]
> Hi @melihhakanpektas , 
> 
> I am new generating sound. But I found that most sf2 files contains multiple instruments. 
> However this lib does not seem to care.
> 
> Is there any support for that? Or could you give me a hint how to work with that? (If successfull I would be more then willing to create a pull request.)

Very good timing. I will push an update within 24 hours 🙂

**Comment by KapitanPL** [comment]
Great work, thanks. 

No I have to learn how to work with them. :)
